// <auto-generated />
namespace Pizza_Uyg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20220224 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20220224));
        
        string IMigrationMetadata.Id
        {
            get { return "202202241609009_20220224"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
